config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  scope module: :user do
    root to: "homes#top"
    resources :bikes, only: [:new, :create, :index, :show, :destroy] do
      resources :bike_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update]
    # 退会確認画面
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    # 論理削除用のルーティング
    patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
  end


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    resources :bikes, only: [:show, :destroy]
    resources :users, only: [:index, :show, :update]
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  #管理側はレビュー一覧ページを"bikes_controller"では管理しない。
  def top
    @bikes = Bike.page(params[:page])
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/views/admin/homes/top.html.erb
<h1>管理者トップ（レビュー一覧）</h1>

<table class="table table-hover">
  <thead>
    <th>投稿日</th>
    <th>ユーザー</th>
    <th>画像</th>
    <th>メーカー / 車種</th>
    <th>第一印象</th>
    <th>いいね / コメント数</th>
  </thead>
  <tbody>
    <% @bikes.each do |bike| %>
      <tr>
        <td><%= bike.created_at.strftime('%Y/%m/%d') %></td>
        <td>
          <%= link_to admin_user_path(bike.user) do %>
          <%= bike.user.name %>
          <% end %>
        </td>
        <td><%= image_tag bike.get_bike_image(100,100) %></td>
        <td><%= bike.manufacturer %> / <%= link_to bike.bike_name, admin_bike_path(bike.id) %></td>
        <td><%= bike.first_impression %></td>
        <td>♡<%= bike.favorites.count %> / <%= bike.bike_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @bikes %>