config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  scope module: :user do
    root to: "homes#top"
    resources :bikes, only: [:new, :create, :index, :show, :destroy] do
      resources :bike_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update]
    # 退会確認画面
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    # 論理削除用のルーティング
    patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
  end


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    resources :bikes, only: [:show, :destroy]
    resources :users, only: [:index, :show, :update]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :bikes, dependent: :destroy
  has_many :bike_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
         
  has_one_attached :user_image
  
  validates :name, presence:true, uniqueness:true, length:{minimum: 2, maximum: 20}
  validates :introduction, length:{maximum: 50}
  
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  def get_user_image(width, height)
    unless user_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      user_image.attach(io: File.open(file_path), filename: 'default-image.jpeg', content_type: 'image/jpeg')
    end
    user_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @bikes = @user.bikes.page(params[:page])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to admin_user_path(@user.id)
    # 管理側では、全てのユーザーの会員ステータス（会員or退会）の選択ができる
  end
  
  
  
  # ユーザーデータのストロングパラメーター
  private
  
  def user_params
    params.require(:user).permit(:name, :introduction, :user_image, :is_deleted)
  end
end

app/controllers/user/bike_comments_controller.rb
class User::BikeCommentsController < ApplicationController
  before_action :authenticate_user!, except: [:destroy
  ]
  
  def create
    bike = Bike.find(params[:bike_id])
    comment = current_user.bike_comments.new(bike_comment_params)
    comment.bike_id = bike.id
    if comment.save
      flash[:notice] = "Bike comment was successfully created."
      redirect_to bike_path(bike)
    else
      #@error_comment = comment
      #@bike = Bike.find(params[:bike_id])
      #@bike_comment = BikeComment.new
      #render "user/bikes/show"
      
      #エラーメッセージ表示のため"render"を使うとエラーが起こるため、"redirect_to"で実装
      #エラーメッセージは未実装
      redirect_to bike_path(bike)
    end
  end
  
  def destroy
    BikeComment.find(params[:id]).destroy
    flash[:notice] = "Bike comment was successfully destroyed."
    redirect_to bike_path(params[:bike_id])
  end

  #コメントデータのストロングパラメーター
  private

  def bike_comment_params
    params.require(:bike_comment).permit(:comment)
  end
end

app/controllers/user/bikes_controller.rb
class User::BikesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :destroy
  ]

  def new
    @bike = Bike.new
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.user_id = current_user.id
    if @bike.save
      flash[:notice] = "Bike review was successfully created."
      redirect_to bike_path(@bike)
    else
      render :new
    end
  end

  def index
    @bikes = Bike.page(params[:page])
  end

  def show
    @bike = Bike.find(params[:id])
    @bike_comment = BikeComment.new
  end

  def destroy
    bike = Bike.find(params[:id])
    bike.destroy
    flash[:notice] = "Bike review was successfully destroyed."
    redirect_to '/bikes'
  end

  # 投稿データのストロングパラメーター
  private

  def bike_params
    params.require(:bike).permit(:bike_image, :manufacturer, :bike_name, :first_impression, :body)
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  before_action :authenticate_user!
  
  def create
    bike = Bike.find(params[:bike_id])
    favorite = current_user.favorites.new(bike_id: bike.id)
    favorite.save
    redirect_to bike_path(bike)
  end

  def destroy
    bike = Bike.find(params[:bike_id])
    favorite = current_user.favorites.find_by(bike_id: bike.id)
    favorite.destroy
    redirect_to bike_path(bike)
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  before_action :user_state, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    bikes_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def user_state
    @user = User.find_by(email: params[:user][:email])
    return if !@user
    if @user.valid_password?(params[:user][:password]) && (@user.is_deleted == true)
      flash[:notice] = "You have withdrawn. Please register again and use it."
      redirect_to new_user_registration_path
    end
  end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :ensure_user, except: [:index]

  def index
    @users = User.page(params[:page])
  end

  def show
    @bikes = @user.bikes.page(params[:page])
  end

  def edit
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def unsubscribe
    if @user == current_user
      # 退会確認画面への移動
      render "unsubscribe"
    else
      redirect_to user_path(current_user)
    end
  end

  def withdrawal
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "You have withdrawn user successfully"
    redirect_to root_path
    # アカウントは物理削除されない
    # is_deletedカラムをtrueに変更することにより退会フラグを立てる
  end
  
  def ensure_user
    @user = User.find(params[:id])
  end

  # ユーザーデータのストロングパラメーター
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :user_image, :is_deleted)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/bike_comments_helper.rb
module User::BikeCommentsHelper
end

app/helpers/user/bikes_helper.rb
module User::BikesHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/user/users/edit.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto text-center shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light py-4 mb-0">プロフィール編集</h5>
      <div class="form-body p-4">
        <% if @user.errors.any? %>
        <%= @user.errors.count %>件のエラーが発生しました
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @user do |f| %>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-user"></i></span>
            </div>
            <%= f.text_field :name, autofocus:true, class: "form-control", id:"inputName", placeholder:"ユーザー名" %>
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-pen"></i></span>
            </div>
            <%= f.text_area :introduction, class: "form-control", rows:"3", id:"inputIntroduction", placeholder:"自己紹介文" %>
          </div>
          <div class="input-group my-3">
            <label><%= f.file_field :user_image, placeholder: "プロフィール画像", class: "w-100" %></label>
          </div>
          <hr>
          <%= f.submit "変更を保存", class: "btn btn-lg btn-block btn-info mt-5" %>
          <%= link_to "退会する", unsubscribe_path, class: "btn btn-lg btn-block btn-danger btn-info mt-5" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user/users/index.html.erb
<h1>ユーザー一覧</h1>

<table class="table table-hover">
  <thead>
    <th>プロフィール画像</th>
    <th>ユーザー名</th>
    <th>自己紹介</th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_user_image(100,100), fallback: "no_image.jpeg" %></td>
	  	  <td><%= link_to user.name, "/users/#{user.id}" %></td>
	  	  <td><%= user.introduction %></td>
	  	</tr>
  	<% end %>
  </tbody>
</table>
<%= paginate @users %>

app/views/user/users/show.html.erb
<table>
  <tr><%= image_tag @user.get_user_image(150,150) %></tr>
  <tr>
	  <th>ユーザー名：</th>
	  <th><%= @user.name %></th>
  </tr>
  <tr>
	  <th>　自己紹介：</th>
	  <th><%= @user.introduction %></th>
  </tr>
</table>
<br>
<div>
  <% if @user == current_user %>
    <h5><%= link_to "プロフィール編集", edit_user_path(@user), class: "btn btn-info" %></h5>
  <% end %>
</div>
<br>
<h3><%= @user.name %>さんのレビュー一覧</h3>
<table class="table table-hover">
  <thead>
    <th>投稿日</th>
    <th>画像</th>
    <th>メーカー / 車種</th>
    <th>第一印象</th>
    <th>いいね / コメント数</th>
  </thead>
  <tbody>
    <% @bikes.each do |bike| %>
      <tr>
        <td><%= bike.created_at.strftime('%Y/%m/%d') %></td>
        <td><%= image_tag bike.get_bike_image(150,150) %></td>
        <td><%= bike.manufacturer %> / <%= link_to bike.bike_name, bike_path(bike.id) %></td>
        <td><%= bike.first_impression %></td>
        <td>♡<%= bike.favorites.count %> / <%= bike.bike_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @bikes %>

app/views/user/users/unsubscribe.html.erb
<h2 class="text-center">退会お手続き</h2>
<br>
<h5 class="text-center">
  退会するとレビューの新規投稿と、いいね・コメント機能がご利用頂けなくなります。<br>
  また、退会されましても新規投稿を行なったレビューと、記入したコメントは残り続けます。<br>
  お手数お掛けしますが、レビューとコメントを削除されたい場合は、<br>
  退会お手続きの前にレビューとコメントの削除をお願い致します。
</h5>
<br>
<div class="container">
  <div class="row">
    <div class="mx-auto col-md-3">
      <%= link_to "退会する", withdrawal_path, method: :patch, "data-confirm" => "本当に退会しますか？", class: "btn btn-block btn-danger" %>
    </div>
    <div class="mx-auto col-md-3">
      <%= link_to "退会しない", user_path(current_user), class: "btn btn-block btn-primary" %>
    </div>
  </div>
</div>