config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  scope module: :user do
    root to: "homes#top"
    resources :bikes, only: [:new, :create, :index, :show, :destroy] do
      resources :bike_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update]
    # 退会確認画面
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    # 論理削除用のルーティング
    patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
  end


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    resources :bikes, only: [:show, :destroy]
    resources :users, only: [:index, :show, :update]
  end
end

app/models/bike.rb
class Bike < ApplicationRecord

  belongs_to :user
  has_many :bike_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :bike_image
  
  validates :bike_image, presence:true
  validates :manufacturer, presence:true, length:{maximum:30}
  validates :bike_name, presence:true, length:{maximum:30}
  validates :first_impression, presence:true, length:{maximum:30}
  validates :body, presence:true, length:{maximum:400}

  def get_bike_image(width, height)
    unless bike_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      bike_image.attach(io: File.open(file_path), filename: 'default-image.jpeg', content_type: 'image/jpeg')
    end
    bike_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :bikes, dependent: :destroy
  has_many :bike_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
         
  has_one_attached :user_image
  
  validates :name, presence:true, uniqueness:true, length:{minimum: 2, maximum: 20}
  validates :introduction, length:{maximum: 50}
  
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  def get_user_image(width, height)
    unless user_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      user_image.attach(io: File.open(file_path), filename: 'default-image.jpeg', content_type: 'image/jpeg')
    end
    user_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/bikes_controller.rb
class Admin::BikesController < ApplicationController
  before_action :authenticate_admin!

  def show
    @bike = Bike.find(params[:id])
  end

  def destroy
    bike = Bike.find(params[:id])
    bike.destroy
    flash[:notice] = "Bike review was successfully destroyed."
    redirect_to '/admin/top'
    # 管理側は全てのユーザーのレビューを削除できる
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @bikes = @user.bikes.page(params[:page])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to admin_user_path(@user.id)
    # 管理側では、全てのユーザーの会員ステータス（会員or退会）の選択ができる
  end
  
  
  
  # ユーザーデータのストロングパラメーター
  private
  
  def user_params
    params.require(:user).permit(:name, :introduction, :user_image, :is_deleted)
  end
end

app/controllers/user/bike_comments_controller.rb
class User::BikeCommentsController < ApplicationController
  before_action :authenticate_user!, except: [:destroy
  ]
  
  def create
    bike = Bike.find(params[:bike_id])
    comment = current_user.bike_comments.new(bike_comment_params)
    comment.bike_id = bike.id
    if comment.save
      flash[:notice] = "Bike comment was successfully created."
      redirect_to bike_path(bike)
    else
      #@error_comment = comment
      #@bike = Bike.find(params[:bike_id])
      #@bike_comment = BikeComment.new
      #render "user/bikes/show"
      
      #エラーメッセージ表示のため"render"を使うとエラーが起こるため、"redirect_to"で実装
      #エラーメッセージは未実装
      redirect_to bike_path(bike)
    end
  end
  
  def destroy
    BikeComment.find(params[:id]).destroy
    flash[:notice] = "Bike comment was successfully destroyed."
    redirect_to bike_path(params[:bike_id])
  end

  #コメントデータのストロングパラメーター
  private

  def bike_comment_params
    params.require(:bike_comment).permit(:comment)
  end
end

app/controllers/user/bikes_controller.rb
class User::BikesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :destroy
  ]

  def new
    @bike = Bike.new
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.user_id = current_user.id
    if @bike.save
      flash[:notice] = "Bike review was successfully created."
      redirect_to bike_path(@bike)
    else
      render :new
    end
  end

  def index
    @bikes = Bike.page(params[:page])
  end

  def show
    @bike = Bike.find(params[:id])
    @bike_comment = BikeComment.new
  end

  def destroy
    bike = Bike.find(params[:id])
    bike.destroy
    flash[:notice] = "Bike review was successfully destroyed."
    redirect_to '/bikes'
  end

  # 投稿データのストロングパラメーター
  private

  def bike_params
    params.require(:bike).permit(:bike_image, :manufacturer, :bike_name, :first_impression, :body)
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  before_action :authenticate_user!
  
  def create
    bike = Bike.find(params[:bike_id])
    favorite = current_user.favorites.new(bike_id: bike.id)
    favorite.save
    redirect_to bike_path(bike)
  end

  def destroy
    bike = Bike.find(params[:bike_id])
    favorite = current_user.favorites.find_by(bike_id: bike.id)
    favorite.destroy
    redirect_to bike_path(bike)
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  before_action :user_state, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    bikes_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def user_state
    @user = User.find_by(email: params[:user][:email])
    return if !@user
    if @user.valid_password?(params[:user][:password]) && (@user.is_deleted == true)
      flash[:notice] = "You have withdrawn. Please register again and use it."
      redirect_to new_user_registration_path
    end
  end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :ensure_user, except: [:index]

  def index
    @users = User.page(params[:page])
  end

  def show
    @bikes = @user.bikes.page(params[:page])
  end

  def edit
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def unsubscribe
    if @user == current_user
      # 退会確認画面への移動
      render "unsubscribe"
    else
      redirect_to user_path(current_user)
    end
  end

  def withdrawal
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "You have withdrawn user successfully"
    redirect_to root_path
    # アカウントは物理削除されない
    # is_deletedカラムをtrueに変更することにより退会フラグを立てる
  end
  
  def ensure_user
    @user = User.find(params[:id])
  end

  # ユーザーデータのストロングパラメーター
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :user_image, :is_deleted)
  end
end

app/helpers/admin/bikes_helper.rb
module Admin::BikesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/bike_comments_helper.rb
module User::BikeCommentsHelper
end

app/helpers/user/bikes_helper.rb
module User::BikesHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/views/user/bikes/index.html.erb
<h1>レビュー一覧</h1>

<table class="table table-hover">
  <thead>
    <th>投稿日</th>
    <th>ユーザー</th>
    <th>画像</th>
    <th>メーカー / 車種</th>
    <th>第一印象</th>
    <th>いいね / コメント数</th>
  </thead>
  <tbody>
    <% @bikes.each do |bike| %>
      <tr>
        <td><%= bike.created_at.strftime('%Y/%m/%d') %></td>
        <td>
          <%= link_to user_path(bike.user) do %>
          <%= bike.user.name %>
          <% end %>
        </td>
        <td><%= image_tag bike.get_bike_image(100,100) %></td>
        <td><%= bike.manufacturer %> / <%= link_to bike.bike_name, bike_path(bike.id) %></td>
        <td><%= bike.first_impression %></td>
        <td>♡<%= bike.favorites.count %> / <%= bike.bike_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @bikes %>

app/views/user/bikes/new.html.erb
<div class="containar">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark text-center bg-light p-4 mb-0">新規投稿フォーム</h5>
      <div class="form-body p-4">
        <% if @bike.errors.any? %>
        <%= @bike.errors.count %>件のエラーが発生しました
          <ul>
            <% @bike.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @bike do |f| %>
          <h6>画像</h6>
          <%= f.file_field :bike_image, accept: "image/*", class: "w-100" %>
          <h6>メーカ名</h6>
          <%= f.text_field :manufacturer, class: "form-control" %>
          <h6>車種名</h6>
          <%= f.text_field :bike_name, class: "form-control" %>
          <h6>第一印象（一言で）</h6>
          <%= f.text_area :first_impression, class: "form-control" %>
          <h6>感想</h6>
          <%= f.text_area :body, class: "form-control", rows:"3" %>
          <hr>
          <%= f.submit '投稿', class: "btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user/bikes/show.html.erb
<div class="container">
  <div class="row">
    <h3><%= @bike.user.name %>さんのレビュー</h3>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= image_tag @bike.get_bike_image(200,200) %>
    </div>
    <div class="col-md-8 py-5">
      <table>
        <tr><td>投稿日：<%= @bike.created_at.strftime('%Y/%m/%d') %></td></tr>
        <tr><td>メーカー：<%= @bike.manufacturer %></td></tr>
        <tr><td>車種：<%= @bike.bike_name %></td></tr>
        <tr><td>第一印象：<%= @bike.first_impression %></td></tr>
      </table>
    </div>
  </div>
  <div>
    <p>感想：<%= @bike.body %></p>
    <% if @bike.user == current_user %>
      <%= link_to "削除", bike_path(@bike.id), class: "btn btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %>
    <% end %>
  </div>
  <br>
  <div>
    <% if current_user.nil? %>
      <p>♡<%= @bike.favorites.count %> いいね</p>
    <% elsif @bike.favorited_by?(current_user) %>
      <p>
        <%= link_to bike_favorites_path(@bike), method: :delete do %>
          ♥<%= @bike.favorites.count %> いいね
        <% end %>
      </p>
    <% else %>
      <p>
        <%= link_to bike_favorites_path(@bike), method: :post do %>
          ♡<%= @bike.favorites.count %> いいね
        <% end %>
      </p>
    <% end %>
  </div>
  <div class="new-comment card-text">
    <% if user_signed_in? %>
      <%= form_with model: [@bike, @bike_comment] do |f| %>
        <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
        <%= f.submit "送信する", class: "btn btn-primary" %>
      <% end %>
    <% end %>
  </div>
  <hr>
  <div class="comments card-text">
  <h4><%= @bike.bike_comments.count %>件コメント</h4>
  <% @bike.bike_comments.each do |bike_comment| %>
    <div class="media border mb-3">
      <%= bike_comment.user.name %>
      <%= image_tag bike_comment.user.get_user_image(60,60), class: "bd-placeholder-img align-self-center mx-3" %>
      <div class="media-body ml-4 p-3">
        <p><%= bike_comment.created_at.strftime('%Y/%m/%d') %></p>
        <p><%= bike_comment.comment %></p>
        <% if bike_comment.user == current_user %>
          <%= link_to "削除", bike_bike_comment_path(bike_comment.bike, bike_comment), method: :delete, class: "btn btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %>
        <% end %>
      </div>
    </div>
  <% end %>
  </div>
</div>