config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  scope module: :user do
    root to: "homes#top"
    resources :bikes, only: [:new, :create, :index, :show, :destroy] do
      resources :bike_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update]
    # 退会確認画面
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    # 論理削除用のルーティング
    patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
  end


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    resources :bikes, only: [:show, :destroy]
    resources :users, only: [:index, :show, :update]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord

  belongs_to :user
  has_many :bike_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :bike_image
  
  validates :bike_image, presence:true
  validates :manufacturer, presence:true, length:{maximum:30}
  validates :bike_name, presence:true, length:{maximum:30}
  validates :first_impression, presence:true, length:{maximum:30}
  validates :body, presence:true, length:{maximum:400}

  def get_bike_image(width, height)
    unless bike_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      bike_image.attach(io: File.open(file_path), filename: 'default-image.jpeg', content_type: 'image/jpeg')
    end
    bike_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/bike_comment.rb
class BikeComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :bike
  
  validates :comment, presence: true, length:{maximum:200}
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :bike
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :bikes, dependent: :destroy
  has_many :bike_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
         
  has_one_attached :user_image
  
  validates :name, presence:true, uniqueness:true, length:{minimum: 2, maximum: 20}
  validates :introduction, length:{maximum: 50}
  
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  def get_user_image(width, height)
    unless user_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      user_image.attach(io: File.open(file_path), filename: 'default-image.jpeg', content_type: 'image/jpeg')
    end
    user_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/bikes_controller.rb
class Admin::BikesController < ApplicationController
  before_action :authenticate_admin!

  def show
    @bike = Bike.find(params[:id])
  end

  def destroy
    bike = Bike.find(params[:id])
    bike.destroy
    flash[:notice] = "Bike review was successfully destroyed."
    redirect_to '/admin/top'
    # 管理側は全てのユーザーのレビューを削除できる
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/user/bikes_controller.rb
class User::BikesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :destroy
  ]

  def new
    @bike = Bike.new
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.user_id = current_user.id
    if @bike.save
      flash[:notice] = "Bike review was successfully created."
      redirect_to bike_path(@bike)
    else
      render :new
    end
  end

  def index
    @bikes = Bike.page(params[:page])
  end

  def show
    @bike = Bike.find(params[:id])
    @bike_comment = BikeComment.new
  end

  def destroy
    bike = Bike.find(params[:id])
    bike.destroy
    flash[:notice] = "Bike review was successfully destroyed."
    redirect_to '/bikes'
  end

  # 投稿データのストロングパラメーター
  private

  def bike_params
    params.require(:bike).permit(:bike_image, :manufacturer, :bike_name, :first_impression, :body)
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :ensure_user, except: [:index]

  def index
    @users = User.page(params[:page])
  end

  def show
    @bikes = @user.bikes.page(params[:page])
  end

  def edit
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def unsubscribe
    if @user == current_user
      # 退会確認画面への移動
      render "unsubscribe"
    else
      redirect_to user_path(current_user)
    end
  end

  def withdrawal
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "You have withdrawn user successfully"
    redirect_to root_path
    # アカウントは物理削除されない
    # is_deletedカラムをtrueに変更することにより退会フラグを立てる
  end
  
  def ensure_user
    @user = User.find(params[:id])
  end

  # ユーザーデータのストロングパラメーター
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :user_image, :is_deleted)
  end
end

app/helpers/admin/bikes_helper.rb
module Admin::BikesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/bike_comments_helper.rb
module User::BikeCommentsHelper
end

app/helpers/user/bikes_helper.rb
module User::BikesHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bikers review</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bikers review</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
              <li class="nav-item">
                <%= link_to admin_top_path, class: "nav-link text-light" do %>
                  <i class="fas fa-motorcycle"></i> レビュー一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_users_path, class: "nav-link text-light" do %>
                  <i class="fas fa-users"></i> ユーザー一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link text-light" do %>
                  <i class="fas fa-sign-out-alt"></i> ログアウト
                <% end %>
              </li>
            <% elsif user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
                  <i class="fas fa-user"></i> マイページ
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to bikes_path, class: "nav-link text-light" do %>
                  <i class="fas fa-motorcycle"></i> レビュー一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path, class: "nav-link text-light" do %>
                  <i class="fas fa-users"></i> ユーザー一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_bike_path, class: "nav-link text-light" do %>
                  <i class="fas fa-pen"></i> 投稿フォーム
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                  <i class="fas fa-sign-out-alt"></i> ログアウト
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to bikes_path, class: "nav-link text-light" do %>
                  <i class="fas fa-motorcycle"></i> レビュー一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path, class: "nav-link text-light" do %>
                  <i class="fas fa-users"></i> ユーザー一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                  <i class="fas fa-user-plus"></i> 新規登録
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                  <i class="fas fa-sign-in-alt"></i> ログイン
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <p class="notice"><%= notice %></p>
    </main>
    <%= yield %>
  </body>
</html>